### PR TITLE
Anchor / Static outputs and filtering options

### PR DESCRIPTION
**Pull request by TrezorHannes**
- ability to `--filter anchors || static`
- show anchor or static for each output

### CODE REVIEW

**Review by blckbx — APPROVED** [review]
:fire:

**Comment by blckbx** [comment]
```
$ bash anc.sh --type anchors --limit 50
anc.sh: line 129: [: --limit: integer expression expected
```
running into issues specifying `--type` and `--limit`

**Comment by TrezorHannes** [comment]
> ```
> $ bash anc.sh --type anchors --limit 50
> anc.sh: line 129: [: --limit: integer expression expected
> ```
> 
> running into issues specifying `--type` and `--limit`

Fixed this with [0140267](https://github.com/blckbx/NodeTools/pull/16/commits/01402671907512c7e9b4a4a0cfb13868db19dac3)

**Review by blckbx — COMMENTED** [review]
Works! Guess this needs to be specified for each command. Combining `--type` and `--peer` also throws same error.

**Comment by TrezorHannes** [comment]
> Works! Guess this needs to be specified for each command. Combining `--type` and `--peer` also throws same error.

I don't catch this error cause it's stupid to enter in the first place 🙈

**Pull request merged**
